### ISSUE TITLE
The app doesn't work after install

### ISSUE THREAD

**Issue by pablorq** [phpawy/jims_inventory_management#1]
Hi!

I've installed the unzipde folder inside a WAMP server.

The page 127.0.0.1/jims returns nothing and Firefox shows a list of files and folders. A clic in the server.php file show this error:

Warning: require(C:\wamp\www\jims\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp\www\jims\bootstrap\autoload.php on line 17

Any idea of what could be happening?

There's any missing configuration?

Regards...

**Comment by phpawy** [comment]
Hello

did you run "composer install" ?

As the system is built upon Laravel 5, you will need to run this command to install dependencies.

Regards

**Comment by pablorq** [comment]
Hi!

After run 'composer install' now I have:
- http:localhost/jims/
Again the list of files and folders from Firefox

- http://127.0.0.1/jims/server.php
Error message: 'Whoops, looks like something went wrong.'

Any idea?

Regards...

**Comment by phpawy** [comment]
Hi parq

This is related to Laravel framework. please make sure to follow their installation guide.

Thanks

**Comment by pablorq** [comment]
Hi,

Now I have some advance...

After rename '.env.example' to '.env', run 'php artisan key:generate', create a new database and setup it in the '.env' file, now I see a page in http://127.0.0.1/jims/public/, but when I try to do something I get an exception because there's nothing on the db.

How can I populate the db? There's no *.sql file to do this.

Thank you in advance...

**Comment by phpawy** [comment]
Hello

You will need to run migrations.

Regards
